### ISSUE TITLE
HelloController

### ISSUE THREAD

**Issue by dimik12211** [dimik12211/LabMOSm-221#1]
Написать класс контроллеров HelloController. Содержание класса:
1) Get Метод с ендпоинтом "/hello"
1.1) Метод должен вернуть .html файл с соответствующим именем
2) Post Метод с ендпоинтом "/hello"
2.1) Метод получает в параметре массив файлов, необходимо передать данные файлы в метод по созданию архива.

**Comment by sergey43999** [comment]
@dimik12211 Уточни, пжл, "файл с соответтвующим именем" это каким?

**Comment by dimik12211** [comment]
@sergey43999 Имя файла: hello.html
Путь: resources/templates

**Comment by sergey43999** [comment]
@dimik12211 А также предлагаю маппинг контроллеров изменить с /hello на 
1)/getDownload
2)/postDownload
Для того чтобы было интуитивно понятно в дальнейшем для чего они используются

**Comment by sergey43999** [comment]
@dimik12211 Задача выполнена закрываю
