### ISSUE TITLE
Create ZIP

### ISSUE THREAD

**Issue by dimik12211** [dimik12211/LabMOSm-221#3]
Создать метод "create ZIP" в классе FileService

Необходимо создать метод под названием createZip, который будет выполнять архивацию загруженных пользователем файлов
Возвращаемое значение: Uid архива

**Comment by sergey43999** [comment]
@dimik12211 Также прикладываю PR к задаче, для дальнейшей простой навигации по проекту 

https://github.com/dimik12211/LabMOSm-221/pull/6
